name = "hono-cloudflare-d1"
main = "src/index.ts"
compatibility_date = "2024-10-20"
compatibility_flags = [ "nodejs_compat" ]

[vars]
OWNER = "Sayed Tahsin"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "hono-cfw-d1"
database_id = "466bae14-afc8-431c-9670-c6c067364108"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1